version: '3'

services:
  server:
    container_name: back
    build:
      context: ./Backend
    ports:
      - "8080:8080"

  client:
    container_name: front
    build:
      context: ./frontend
    depends_on:
      - server
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    build: ./.nginx
    depends_on:
      - server
      - client
    volumes:
      - ./.nginx:/etc/nginx/conf.d
      - ./.nginx/zerossl:/var/www/zerossl/.well-known/pki-validation
      - ./.nginx/cert:/cert
    ports:
      - 80:80
      - 443:443
