server.port: 8080

spring:
  datasource:
    url : jdbc:mysql://3.34.201.176/bigdata?serverTimezone=Asia/Seoul          # ssafy EC2 발급되면 변경 예정
    username : root
    password : 12345
    hikari:
      maximum-pool-size: 8