server.port: 8080

spring:
  datasource:
    url : jdbc:mysql://3.34.201.176/bigdata?serverTimezone=Asia/Seoul          # ssafy EC2 발급되면 변경 예정
    username : root
    password : 12345
    hikari:
      maximum-pool-size: 8


token:
  accesstoken: "accessToken"
  refreshtoken: "refreshToken"
  expire:                        # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    accesstoken: 3600000
    refreshtoken: 604800000
  secretkey: "jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg"


