build:
  date: '@build.date@'

logging:
  level:
    org:
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
      sringframework:
        boot: DEBUG
        security: DEBUG
    root: INFO

server.port: 8080

spring:
  datasource:
    url : jdbc:mysql://k5a305.p.ssafy.io:3306/metamong?serverTimezone=Asia/Seoul          # ssafy EC2 발급되면 변경 예정
    username : root
    password : 12345
    hikari:
      maximum-pool-size: 8

  redis:
    host: k5a305.p.ssafy.io
    port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comment: true

  mvc:
    throw-exception-if-no-handler-found: false

    data:
      web:
        pageable:
          one-indexed-parameters: true

    web:
      resources:
        #      add-mappings: false
        static-locations: classpath:/dist/

    devtools:
      livereload:
        enabled: true

  security:
    user:
      name: user
      password: 12345

token:
  accesstoken: "accessToken"
  refreshtoken: "refreshToken"
  expire:                        # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    accesstoken: 3600000
    refreshtoken: 604800000
  secretkey: "jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg"

