build:
  date: '@build.date@'

logging:
  level:
    org:
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
      sringframework:
        boot: DEBUG
        security: DEBUG
    root: INFO

server.port: 8080

---

spring:
  profiles:
    active: prod
    
    
---


token:
  accesstoken: "accessToken"
  refreshtoken: "refreshToken"
  expire:                        # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    accesstoken: 3600000
    refreshtoken: 604800000
  secretkey: "jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg"

